name: Weekly AI-Powered Posts

on:
  schedule:
    # Runs every Monday at 9am IST (3:30am UTC)
    - cron: "30 3 * * 1"
  workflow_dispatch:

jobs:
  run-ai-posts:
    runs-on: ubuntu-latest
    env:
      PERSONAL_GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
      PERSONAL_GITHUB_USERNAME: ${{ secrets.PERSONAL_GITHUB_USERNAME }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
      NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run AI-powered posts script
        run: |
          python src/main.py
